language: javascript
sudo: required

install:
  # Get the scripts required to validate shtml files
 - wget https://gist.githubusercontent.com/camieac/ba85ae8df60c5d158e2b6dae93932ceb/raw/3322a3914292923e83484c376eb6ec26ffd2f0bc/ejs_parse.py
 - wget https://gist.githubusercontent.com/camieac/d9d54f6ad4996d2b2b287fd4d82bdd6a/raw/447f52661a60bd1a653d1ec92d951406c02f6b7d/validate.py
 - chmod +x ejs_parse.py
 - chmod +x validate.py
 - pip install requests

script:
  - mkdir ejs_parsed_public_html
  # Validate index.(x)html
  - ./ejs_parse.py -i views/index.ejs -o ejs_parsed_public_html/index.html -r views/
  - ./validate.py -i ejs_parsed_public_html/index.html
  #Validate settings.(x)html
  - ./ejs_parse.py -i views/settings.ejs -o ejs_parsed_public_html/settings.html -r views/
  - ./validate.py -i ejs_parsed_public_html/settings.html
  # Validate login.(x)html
  - ./ejs_parse.py -i views/login.ejs -o ejs_parsed_public_html/login.html -r views/
  - ./validate.py -i ejs_parsed_public_html/login.html
  # Validate about.x(html)
  - ./ejs_parse.py -i views/about.ejs -o ejs_parsed_public_html/about.html -r views/
  - ./validate.py -i ejs_parsed_public_html/about.html
