language: javascript
sudo: required

install:
  # Get the scripts required to validate shtml files
 - wget https://gist.githubusercontent.com/camieac/26e5e7f70c5b687854eafdb76a393e39/raw/fa0aa07b222d1323532dada647ddbc4c147ba6e0/ssi_parse.py
 - wget https://gist.githubusercontent.com/camieac/d9d54f6ad4996d2b2b287fd4d82bdd6a/raw/a26a41cab6a512ead33648fe39d3067a2e84c5a3/validate.py
 - chmod +x ssi_parse.py
 - chmod +x validate.py
 - pip install requests

script:
  # Validate index.shtml
  - mkdir ssi_parsed_public_html
  - ./ssi_parse.py -i public_html/index.shtml -o ssi_parsed_public_html/index.shtml -r public_html/
  - ./validate.py ssi_parsed_public_html/index.shtml
